# Generated by Django 5.1.6 on 2025-02-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADRP', '0001_initial'),
    ]

    operations = [
    ]
