# Generated by Django 5.1.6 on 2025-03-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADRP', '0003_remove_review_dataset_remove_datasetfile_dataset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='instance_representation',
            field=models.CharField(blank=True, help_text='What do the instances in the dataset represent', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='authors',
            field=models.ManyToManyField(to='ADRP.authors'),
        ),
    ]
