# Generated by Django 5.1.6 on 2025-03-01 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADRP', '0004_authors_collection_instance_representation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='data_of_publication',
        ),
        migrations.AddField(
            model_name='collection',
            name='date_of_publication',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='collection',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
