# Generated by Django 5.1.6 on 2025-08-15 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADRP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadreasons',
            old_name='further_explain',
            new_name='further_explanation',
        ),
    ]
