# Generated by Django 5.1.6 on 2025-07-29 20:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADRP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
