# Generated by Django 5.1.6 on 2025-09-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADRP', '0002_rename_further_explain_downloadreasons_further_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='f_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='l_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
