# Generated by Django 5.1.6 on 2025-09-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADRP', '0003_user_f_name_user_l_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetfile',
            name='file_name',
            field=models.CharField(max_length=100),
        ),
    ]
