# Generated by Django 5.1.6 on 2025-03-10 12:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADRP', '0003_alter_otp_options_remove_otp_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='access_level',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('restricted', 'Restricted')], default='restricted', max_length=20),
        ),
        migrations.AlterField(
            model_name='collection',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Comma-separated keywords for search and filtering.', size=None),
        ),
    ]
