# Generated by Django 5.1.6 on 2025-04-28 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADRP', '0010_alter_collection_doi_link_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_collections', to=settings.AUTH_USER_MODEL),
        ),
        # migrations.AddField(
        #     model_name='user',
        #     name='is_staff',
        #     field=models.BooleanField(default=False),
        # ),
    ]
