# Generated by Django 5.1.6 on 2025-04-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADRP', '0011_collection_rejected_at_collection_rejected_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
