# Generated by Django 5.1.6 on 2025-03-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADRP', '0005_alter_collection_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('admin', 'Admin')], default='external', max_length=20),
        ),
    ]
