# Generated by Django 5.1.6 on 2025-03-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADRP', '0006_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statisics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('author_count', models.IntegerField(default=0)),
                ('collection_count', models.IntegerField(default=0)),
            ],
        ),
    ]
