# Generated by Django 5.1.6 on 2025-03-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADRP', '0007_statisics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statisics',
            new_name='Statistics',
        ),
    ]
