# Generated by Django 5.1.6 on 2025-03-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADRP', '0008_rename_statisics_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='missing_values',
        ),
    ]
